### PR TITLE
implement Walmart API, and adjust search by adding the products from …

### PR DESCRIPTION
**Pull request by Catheriiiine**
…walmart when searching for items.

### CODE REVIEW

**Comment by Pumpkinmann** [comment]
Hi catherine, I am on your branch and looked into what you write. I think it is good so far, but you would need to work on setting api token to environment varaibles, to prevent possible external attacks and illegal use of our api token since it is exposed to the public

**Review by Pumpkinmann — CHANGES_REQUESTED** [review]
Hi catherine, I am on your branch and looked into what you write. I think it is good so far, but you would need to work on setting api token to environment varaibles, to prevent possible external attacks and illegal use of our api token since it is exposed to the public

**Comment by Catheriiiine** [comment]
I made the token environmental and made sure this file runs as what I want. I also edit the gitignore, can you check if that's fine?

**Review by Pumpkinmann — APPROVED** [review]
Hi Catherine, looks good!

**Pull request merged**
